main/apps/login_reg/urls.py
from django.conf.urls import url
from .import views

urlpatterns = [
    url(r'^$', views.index, name='home'),
    url(r'^success$', views.success, name='success'),
    url(r'^create$', views.create, name='create'),
    url(r'^login$', views.login, name='login')
]

main/main/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('apps.login_reg.urls', namespace='index'))
]

main/apps/login_reg/models.py
from django.db import models
import bcrypt
import re

EMAIL_REGEX = re.compile(r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')
#import libraries re and bcrypt

# Create your models here.
class UserManager(models.Manager):
    def validate(self, form):
        errors = []
        #validate the form
        if len(form['first_name']) <2:
            errors.append('First name must be longer than 2 characters.')
        if len(form['last_name']) <2:
            errors.append('Last name must be longer than 2 characters.')
        if not EMAIL_REGEX.match(form['email']):
            errors.append('Email must be valid.')
        if len(form['password']) < 8:
            errors.append('Password must be at least 8 characters long.')
        if form['password'] != form['confirm_pw']:
            errors.append('Passwords much match.')

#if validation passes. now check to see if email is in the db.
        if self.filter(email=form['email']):
            errors.append('Email already in use.')
#if we find errors return them to the function that called in in the views file.
        return errors

    def create_user(self, form_data):
        pw_hash = bcrypt.hashpw(form_data['password'].encode(), bcrypt.gensalt())
        return self.create(
            first_name = form_data['first_name'],
            last_name =form_data['last_name'],
            email = form_data['email'],
            pw_hash = pw_hash,

        )

    def login_user(self, form_data):
        user_list = User.objects.filter(email=form_data['email'])
        if len(user_list) > 0 :
            print(user_list)
            user = user_list[0]
            if bcrypt.checkpw(form_data['password'].encode(), user.pw_hash.encode()):
                return(True, user.id)
            else:
                return(False, "Email or passwords don't match.")
        else:
            return (False, "Email or passwords don't match.")


class User(models.Model):
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    email = models.CharField(max_length=255)
    pw_hash=models.CharField(max_length=500)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

    def __str__(self):
        return self.email

main/apps/login_reg/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.contrib import messages
from .models import User

# Create your views here.
def index(request):
    return render(request, 'login_reg/index.html')

def success(request):
    context = {
        'user' : User.objects.get(id=request.session['user_id'])
    }
    return render(request, 'login_reg/success.html', context)

def create(request):
    errors = User.objects.validate(request.POST)
    if errors:
        for error in errors:
            messages.error(request, error)
        return redirect('index:home')
    user = User.objects.create_user(request.POST)
    request.session['user_id'] = user.id
    #submit the validation request and create user here.
    print(request.POST)
    return redirect ('index:success')

def login(request):
    valid, response = User.objects.login_user(request.POST)
    if valid == True:
        request.session['user_id'] = response
        return redirect('index:success')
    else:
        messages.error(request, response)
    print(request.POST)
    return redirect('index:home')
    

main/apps/login_reg/templates/login_reg/index.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Registration and Login</title>
</head>

<body>
    <div class="container">
    <h1>Registration</h1>
    {% if messages %}
    <ul class="messages">
        {% for message in messages %}
        <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
    <div class="form-container">
        <form action="{% url 'index:create' %}" method="POST">
        {% csrf_token %}
        First Name: <input type="text" name="first_name" id="">
        <br>
        Last Name: <input type="text" name="last_name" id="">
        <br>
        Email: <input type="text" name="email" id="">
        <br>
        Password: <input type="password" name="password" id="">
        <br>
        Confirm PW: <input type="password" name="confirm_pw" id="">
        <br>
        <input class="btn btn-primary" type="submit" value="Register">
        </form>
        <br>
        <h1>Login</h1>
        <form action="{% url 'index:login' %}" method="POST">
        {% csrf_token %}
        Email: <input type="text" name="email" id="">
        <br>
        Password: <input type="password" name="password" id="">
        <br>
        <input class="btn btn-primary" type="submit" value="Login">
        </form>
    </div>
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>

main/apps/login_reg/templates/login_reg/success.html
<!doctype html>
<html lang="en">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">

    <title>Hello, world!</title>
</head>

<body>
    <h1>Success! Welcome {{ user.first_name }} </h1>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy"
        crossorigin="anonymous"></script>
</body>

</html>